name: btl_iot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  salomon_bottom_bar: ^3.3.2
  flutter_bloc: ^8.1.6
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  carousel_slider: ^5.0.0
  lite_rolling_switch: ^1.0.1
  fl_chart: ^0.69.0
  loading_animation_widget: ^1.2.1
  url_launcher: ^6.3.0
  http: ^1.2.2
  get_it: ^7.6.7
  intl: ^0.18.0
  pdfx: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/fonts/
    - assets/pdf/iot.pdf
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito.ttf